### ISSUE TITLE
Companion Application Practice 

### ISSUE THREAD

**Issue by LukeRykta** [LukeRykta/Swift-Practice#7]
Read the "Companion App Communication" on the https://github.com/LukeRykta/Swift-Practice/wiki/Programming page. There are several links that provide a starting point for building a watch companion app from scratch.

**Tasks:**
- [x] Read Companion App Communication article links
- [x] Add code to send a data packet of some kind from watch to iOS when an onscreen button is pressed
- [x] Commit changes to a feature branch
- [x] Pull request feature->develop

**Comment by LukeRykta** [comment]
Nice
