### ISSUE TITLE
Persistent Cache and First Time Startup Detection

### ISSUE THREAD

**Issue by LukeRykta** [LukeRykta/Swift-Practice#8]
We need to be able to enter text in some fields and have it save even after the app has closed. Also, we need a robust way of detecting when our app has been opened for the first time. Do some research on different solutions to these issues and then develop a suitable solution in our practice app

**Tasks**
- [x] #10
- [ ] Test and Implement methods
- [ ] Commit changes to feature branch
- [ ] Pull request feature->develop
