### ISSUE TITLE
Haptic Engine Practice

### ISSUE THREAD

**Issue by LukeRykta** [LukeRykta/Swift-Practice#9]
Continue working on finding a scalable approach to calling for haptic feedback throughout the code. Add to the wiki your findings and any information that other team members can use themselves.

**Tasks:**
- [x] Research Haptic Functions to Find New Utilities
- [x] Test Various Approaches
- [x] Commit Changes to Feature Branch
- [x] Pull Request feature->develop
